---
title: "Writing R packages in R studio - a very simple intro"
author: "Petr Keil"
date: "May 14, 2019"
output: 
  html_document: 
    highlight: tango
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is material that I will use for an approx. 1-hour seminar giving intro
to the very basic of R packaging.

********************************************************************************

# Why R packages?

- Clean and standardized way to **document** and **share** your code (and data!), even if you don't plan to make a big 'cran' package.
- It forces you to organize the code better, and to respect the conventions.
- They are easier to write than you might think.
- They save everyone's time!

********************************************************************************

# Tutorials

Simple, useful, great:  [Hadley Wickham's website](http://r-pkgs.had.co.nz/)

Comprehensive: [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html)

********************************************************************************


# Initialize

Before we start, you might need the following packages:

```
install.packages(c("devtools", "roxygen2", "knitr"))
```

Now we can initialize a package.

**1. From within R console:**

```
package.skeleton("shampoo")
```
Note that all objects and functions that are currently in the R environment are exported!

**2. With R studio:**

File -> New Project -> New Directory -> New Package

********************************************************************************

# What is in the folder?

### R/

That is where the code lives. Good practice is to give each R function its own file, unless...

### DESCRIPTION

This is where the metadata are.

Two important lines are `Imports` and `Suggests`, e.g.:

```
Imports: plyr, raster
Suggests: sp
```

### NAMESPACE

We will skip this for now.

### man/

This is where the help documentaion is. We don't need to worry about this
with `roxygen2`.

### data/

This is where all data and stored objects (non-functions) live. The simplest
way to bundle data with an R package is by putting `.RData` files in here.

If you want the datasets to have their own documentation, insert a `data.R`
file into the R/ folder for roxygen2 to parse.


### Other things: src/ vignettes/ tests/

This is where compiled code, vignettes, and code testing is. All useful, but
we will skip it.

Anyway, if you plan to include C++ code in your package, I strongly recommend
to use a predefined template in R studio, i.e.:

File -> New Project -> New Directory -> R package with C++ code

### README.md, .gitignore, .git

This is all for the GitHub repository, if we have one.

********************************************************************************

# Documentation

It is convenient to use package `roxygen2` to add the documentation directly 
to the .R files.

### For functions
```
#' Function that adds together two numbers.
#' 
#' This is a really cool and complex function that adds two numbers. I have got
#' the inspiration for this from Hadley Wickahm's web.
#' @param x A number.
#' @param y A number.
#' @return The sum of \code{x} and \code{y}.
#' @examples
#' add(1, 1)
#' add(10, 1)
#' @export

add <- function(x, y) 
{
  x + y
}
```

Examples of other useful declarations are:

```
#' @inherit params
#' @import vegan
#' @references Arita H. (2016) Species co-occurrence analysis: pairwise versus
#' matrix-level approaches. Global Ecology and Biogeography, 25: 1397-1400.

```

### For data 

Create `data.R` file in the `R/` folder and for each dataset insert the following
snippet:

```
#' Prices of 50,000 round cut diamonds.
#'
#' A dataset containing the prices and other attributes of almost 54,000
#' diamonds.
#'
#' @format A data frame with 53940 rows and 10 variables:
#' \describe{
#'   \item{price}{price, in US dollars}
#'   \item{carat}{weight of the diamond, in carats}
#'   ...
#' }
#' @source \url{http://www.diamondse.info/}
"diamonds"
```

********************************************************************************

# Making R package available

Let's not care about CRAN and publish through GitHub!

First, create the repository on GitHub.

Second, initialize git for your package, and push it to the repository:

```
git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/petrkeil/shampoo.git
git push -u origin master
```

Now you can install your package on any machine using:

```
library(devtools)
install_github("petrkeil/shampoo")
```


